name: PullRequest

on:
  push:
    branches:
    - main

jobs:
   MaxQtDynamic: 
    runs-on: macos-11

    strategy:
      fail-fast: false

    steps:
    - name: Run the freakin' script
      run: |
        pwd
        ls -la
        ls -la tools
        ls -la tools/building
        ./tools/building/script.bat
