name: PullRequest

on:
  push:
    branches:
    - main

jobs:
   MaxQtDynamic: 
    runs-on: macos-11

    strategy:
      fail-fast: false

    steps:
    - name: clone me
      run: |
        git clone git@github.com:juangpc/testing_readlink.git .
    - name: where am i
      run: |
        pwd
    - name: ls -la
      run: |
        ls -la
    - name: ls -la tools
      run: |
        ls -la tools
    - name: ls -la tools/building
      run: |
        ls -la tools/building
        ./tools/building/script.bat
    - name: ./tools/building/script.bat
      run: |
        ./tools/building/script.bat
